### ISSUE TITLE
TFuel Staked to EEN API Incorrect?

### ISSUE THREAD

**Issue by andrewlunde** [thetatoken/theta-infrastructure-ledger-explorer#28]
I've been using this route to query TFuel staked.

curl -s https://explorer.thetatoken.org:8443/api/stake/totalAmount/tfuel (708,730,340)

It is different from the value reported at https://explorer.thetatoken.org/ as of MN3. (1,247,855,184)

Is it still reporting stakes to the testnet?  For Pre-elite Edge Nodes?

Or is there another API call I should be using now?

-Andrew

**Comment by averytt** [comment]
Hi Andrew,

Yes, you are correct, that is the testnet stake amount. 

Please use: https://explorer.thetatoken.org:8443/api/stake/totalAmount?type=tfuel 

Thanks!
