### ISSUE TITLE
Unable to run crawler locally due to inaccessible node

### ISSUE THREAD

**Issue by msied** [thetatoken/theta-infrastructure-ledger-explorer#3]
`backend/crawler/config.cfg` requires `node` address and port (appears unrelated to aerospike config). In master, this config file points to `ec2-13-56-138-70.us-west-1.compute.amazonaws.com:16888` which timeouts on requests when the crawler is run (`Error: Request Timeout: /rpc`). This instance may be restricting access to an IP whitelist or alternative security group (non-public).

The crawler cannot be run without an accessible, running node to read from. I would like to request either A) opening this instance up, B) additional documentation pointing to another thetatoken repo/codebase which can be run locally in-place with instructions for how to seed it with populated blocks, or C) an aerospike dumpfile so that the explorer itself may be worked on (ex. adding API endpoints) independent of the crawler. Of course, the first two are preferred.

**Comment by jieyilong** [comment]
Thanks for the feedback! You can run a Theta validator node locally following the instructions here: https://github.com/thetatoken/theta-protocol-ledger
