### ISSUE TITLE
Issues syncing from scratch

### ISSUE THREAD

**Issue by muratso** [thetatoken/theta-infrastructure-ledger-explorer#41]
Hey, I was trying to sync everything from scratch and I spun up a new crawler to sync the whole chain. However, I'm getting the following error

```
3/24/2022, 9:52:06 PM[log] progressInfo: {"height":-1,"count":0}
3/24/2022, 9:52:06 PM[log] DB transaction count progress: 0
3/24/2022, 9:52:06 PM[log] crawledBlockHeightProgress:  -1
3/24/2022, 9:52:06 PM[log] height: 0
3/24/2022, 9:52:06 PM[log] Number of upsert PENDING transactions: 0
3/24/2022, 9:52:06 PM[log] Latest block height: 5780
3/24/2022, 9:52:06 PM[log] DB block height progress: -1
3/24/2022, 9:52:06 PM[log] Query block info takes: 63 ms
3/24/2022, 9:52:06 PM[error] Cannot read property 'length' of null | stack: TypeError: Cannot read property 'length' of null
```

I know that the `length of null` error should mean that the node doesn't have that block, but I'm sure my node has it because I'm also pointing to a node syncing from scratch as you can see. FYI I'm syncing my new node from the snapshot in here https://github.com/thetatoken/theta-protocol-ledger/tree/master/integration/mainnet/walletnode

One weird thing I noticed from the logs is that it seems it is trying to sync from the block `-1`, not the block `0`. I tried changing the `startHeight` to 1 in my config to see if it helped, but it didn't. Am I missing something?
Any thoughts here?

Here's my config
```
{
          "mongo": {
              "uri": "__THETA_MONGO_URI__/__THETA_MONGO_DBNAME__"
          },
          "node": {
              "address": "__THETA_COIN_NODE__",
              "port": 16888
          },
          "log": {
              "level": "error"
          },
          "blockchain": {
              "network_id": "mainnet",
              "startHeight": 0
          },
          "accounting": {
              "coinmarketcap_api_key": "COINMARKETCAP_API_KEY",
              "wallet_addresses": [
                  "2416",
                  "3822"
              ]
          },
          "redis": {
              "enabled": true,
              "isCluster": false,
              "host": "__THETA_REDIS_ENDPOINT__",
              "port": 6379,
              "family": 4,
              "db": 0
          },
          "nodeCache": {
              "enabled": false
          },
          "maxBlockPerCrawl": 20,
          "request_timeout_ms": 100000,
          "retrieveTokenStartHeight": 0,
          "defaultThetaChainID": "mainnet"
      }
```

**Comment by muratso** [comment]
cc: @zhenyang-sliver

**Comment by zhenyang-sliver** [comment]
You can try removing the data in mongoDB and start with `"startHeight": 1`, it should work.

**Comment by muratso** [comment]
> You can try removing the data in mongoDB and start with `"startHeight": 1`, it should work.

I ran a `db.dropDatabase` in my mongo. Also a `show dbs` to make sure there wasn't anything there. Changed the `startHeight` to 1 as you suggested but it also didn't work.

Tried the same thing a second time, but this time changing the `retrieveTokenStartHeight` to 1 and it also didn't work.
Is there something that I can manually add in my db to make sure it will start from the block 0?

On my 2 tries, I also saw this, which is probably a sign that the db was clean.
```
3/24/2022, 10:28:52 PM[log] Mongo DB connection succeeded
3/24/2022, 10:28:52 PM[log] error from getLatestRecordAsync: Error: NO_RECORD
```

**Comment by zhenyang-sliver** [comment]
Can you try running this command to check if you have the block 1 on your node? `curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"theta.GetBlockByHeight","params":[{"height": "1"}],"id":1}' http://__THETA_COIN_NODE__:16888/rpc`

If your DB is empty, and set the `startHeight` to 1, it should start from the block 1. You will see something like this in the log.
`progressInfo: {"height":0,"count":0}
DB transaction count progress: 0
crawledBlockHeightProgress:  0
height: 1
...`

**Comment by muratso** [comment]
FYI I tried an older commit and it seems it worked. To be more specific this one e3326bb1bf0fa7f310b1ae94cfe12664ae79c48b
It didn't throw any error and managed to start syncing from block 0. However, when I changed it back to the latest commit, I started getting the same error. 

Querying the block 0 on my node I get this
```
{"jsonrpc":"2.0","id":1,"result":{"chain_id":"mainnet","epoch":"0","height":"0","parent":"0x0000000000000000000000000000000000000000000000000000000000000000","transactions_hash":"0x0000000000000000000000000000000000000000000000000000000000000000","state_hash":"0x7ada5b5bda556a0573364718e37a189043c80fd8defbd9e28d1bf5c1c197316c","timestamp":"1552675026","proposer":"0x0000000000000000000000000000000000000000","hcc":{"Votes":[],"BlockHash":"0x0000000000000000000000000000000000000000000000000000000000000000"},"guardian_votes":null,"elite_edge_node_votes":null,"children":["0xb538784cf4d6c6450eb08af55e7519fa9d2869a64c3b7700f7989d650658fcac"],"status":4,"hash":"0xd8836c6cf3c3ccea0b015b4ed0f9efb0ffe6254db793a515843c9d0f68cbab65","transactions":null}}
```

In the logs, with the clean db I see this
```
3/24/2022, 11:06:28 PM[log] Start a new crawler progress
3/24/2022, 11:06:28 PM[log] progressInfo: {"height":-1,"count":0}
3/24/2022, 11:06:28 PM[log] DB transaction count progress: 0
3/24/2022, 11:06:28 PM[log] crawledBlockHeightProgress:  -1
```

**Comment by zhenyang-sliver** [comment]
To get the log you posted, you still used `startHeight: 0`? If you change the height to 1 it should work. I think the error is caused by the `"transactions": null` in block 0.

**Comment by muratso** [comment]
I've already changed it to `1`.
One thing I noticed in this line https://github.com/thetatoken/theta-infrastructure-ledger-explorer/blob/0d024c041ea6b82ffbde03a0b9c7584550a59213/backend/crawler/jobs/read-block.js#L325
is that if you have `startHeight` set, it will subtract to 1. If the transactions null is really the problem here, I should probably set the `startHeight` to 2.

It's kinda weird that an older version works even with the transaction null thing. And it's even weirder that the older version synced like 500 blocks, and when I deployed the latest one, it tried to start syncing from the `-1` again. I guess I'm missing something here :(

**Comment by muratso** [comment]
So sorry @zhenyang-sliver. It seems this was entirely my fault. My version of the `.cfg` was "ready" for some older commits. This is why it worked with an older commit. But the thing is... it seems at some point the field `network_id` was renamed to `networkId` and I didn't notice this. As soon as I fixed this... everything was working again. So... closing this issue. Thanks for helping me to figure this out
