### ISSUE TITLE
Validation failed to port 9090 with contract verification in test and mainnet network

### ISSUE THREAD

**Issue by Cainuriel** [thetatoken/theta-infrastructure-ledger-explorer#63]
Dear Theta Explorer developers:

I have been trying for several days to verify contracts in the test network with id 365 and there has been no way.

Obviously I have checked that the contract compiles correctly, assign the correct compilation version and other best practice protocol.

I thought I saw that the error is in the listener. 
I pass the captures of a port 9090 that seems to be nobody listening.
![theta-api](https://user-images.githubusercontent.com/37802572/215275894-59391b42-22a1-4b03-a1de-f5c6670f0d7b.png)

![postman-theta](https://user-images.githubusercontent.com/37802572/215275925-f512875f-7f46-4a11-945b-e01537e6faf6.png)

I have created a simple contract for you to check that it cannot be verified.

```solidity
//SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

contract VerificationText {

    address public owner;

     constructor() 

    {
        owner = msg.sender;

    }


    function msgSender() public view  returns (address) {
        return msg.sender;
    }


}

```

compilation version: 0.8.17
[deployed address](https://testnet-explorer.thetatoken.org/account/0xb3806949f3ac5d60d0ebd3ce5554d141b41e42f9#Contract)

**Comment by zhenyang-sliver** [comment]
The 9090 is not a public port, the contract verification on testnet should work now.

**Comment by Negi-Ashish** [comment]
> The 9090 is not a public port, the contract verification on testnet should work now.

How to verify on mainnet ? is it not possible at the moment?

**Comment by Cainuriel** [comment]
![para_mandar](https://user-images.githubusercontent.com/37802572/215351988-2c27bd84-af26-4d46-b3c6-1081744ffc24.png)
I am reopening the issue because I have tried to verify the simple contract previously discussed on mainnet and the same problem occurs. I have changed the subject of the issue because the failure is the same in both networks.

**Comment by zhenyang-sliver** [comment]
Thanks for reporting the issue, it should work now. I just verified your [contract](https://testnet-explorer.thetatoken.org/account/0xb3806949f3ac5d60d0ebd3ce5554d141b41e42f9#Contract) on the testnet and it works. Can you try again on the mainnet?

**Comment by Cainuriel** [comment]
Fantastic, it's working. I have verified the contract without any problems. 

https://explorer.thetatoken.org/account/0xd1926c26996456696f38b1e7e68d4213bc89e748#Contract
